// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    var c, clamp, data, domain, q, quantile, ramp, y;
    y = d3.scale.linear().domain([20, 80]).range([0, 120]);
    console.log(y(30));
    console.log(y(20));
    console.log(y(80));
    console.log(y(90));
    ramp = d3.scale.linear().domain([0, 100]).range(["red", "blue"]);
    console.log(ramp(50));
    clamp = d3.scale.linear().domain([20, 80]).range([0, 120]);
    console.log(clamp(100));
    clamp.clamp(true);
    console.log(clamp(100));
    data = [-2.347, 4, 5.23, -1.234, 6.234, 7.431];
    y = d3.scale.linear().range([0, 120]);
    y.domain([d3.min(data), d3.max(data)]);
    console.log(y.domain());
    console.log(y.nice());
    q = d3.scale.quantize().domain([0, 10]).range([0, 2, 8]);
    console.log(q(0));
    console.log(q(3));
    console.log(q(3.33));
    console.log(q(3.34));
    console.log(q(5));
    console.log(q(6.66));
    console.log(q(6.67));
    console.log(q(8));
    console.log(q(1000));
    c = d3.rgb("violet");
    c.toString();
    c.darker().toString();
    c.darker(2).toString();
    c.brighter().toString();
    c.brighter(0.1).toString();
    c.hsl();
    c.hsl().toString();
    domain = [0, 1, 10, 100, 1000, 10000, 100000, 1000000];
    quantile = d3.scale.quantile().domain(domain).range([0, 10]);
    console.log('quantile', quantile(10));
    console.log('quantile', quantile(100));
    console.log('quantile', quantile(1000));
    return console.log('quantile', quantile(10000));
  });

}).call(this);
